### ISSUE TITLE
Application icons do not show up in dev mode

### ISSUE THREAD

**Issue by koivunej** [jeau/tiddlywiki-sandstorm#3]
Not sure if this is an issue with `vagrant-spk dev` mode, however inspecting the div.app-icon element tells me an svg is present as the background-image emdedded in the html. Image does however show up if I just view the data-url `data:image/svg+xml;base64,PD94b...` into location in chromium. Could this be a limitation with latest chromium in ubuntu 16.04?

```
$ apt-cache policy chromium-browser                                                                                             
chromium-browser:
  Installed: 51.0.2704.79-0ubuntu0.16.04.1.1242
...
```

![icons-not-showing](https://cloud.githubusercontent.com/assets/1081634/18034405/e8c8486c-6d44-11e6-94be-7fe0cb1247ca.png)

**Comment by jeau** [comment]
This dev mode icon occurs only with vagrant-spk dev mode. 
That's OK on my Sandstorm server : https://emf.sandcats.io/ 
you can Sign in, and I will promote you as User

**Comment by koivunej** [comment]
Thanks! I can see some installed apps, but assuming you have installed `tiddlywiki-sandstorm` on your server, it must be visible for your account only?

**Comment by koivunej** [comment]
Great! Sharing the grain worked, we can scratch that off as tested as well. Again I created two tiddlers, removed the first and updated the other.

I can only see the sidebar icon (the app still isn't visible as installed for me) but yeah, I'm convinced that it's not a bug and can close this :)
